# Minimum number of players on the server required to start the vote
min-players: 3

# Voting time in seconds
vote-time: 30

# The percentage of players needed to vote for the vote to pass. Decimal or a number
needed-votes: 0.5

# Command executed when the vote passes. %s will be replaced by the kicked player name
# Example : "kick %s You have been vote kicked off the server!"
# Leave empty to kick the player
command: ""

# True if play sound on vote start
play-sound: true

# If true, lightning will be struck when the vote kick passes
lightning: true